apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-app-pvc # Це ім'я має співпадати з claimName у вашому deployment.yml
spec:
  accessModes:
    - ReadWriteOnce # Це означає, що том може бути змонтований як для читання, так і для запису одним вузлом
  resources:
    requests:
      storage: 1Gi # Запит на 1 гігабайт сховища (ви можете змінити розмір за потребою)
  # storageClassName: standard # Розкоментуйте, якщо ви використовуєте StorageClass (наприклад, для Minikube або хмарних провайдерів)